language: python
dist: xenial
python:
    # - 3.6
      - 3.7
cache: pip
os: linux

install:
  - pip install -r tools/requirements-devel.txt 
  - pip install tools/

script:
  - for f in `find rules -iname '*.yml'`; do
      echo "== rule $f";
      sigmac -I --target sumologic -c tools/config/sumologic.yml $f;
      echo "== json rule $f";
      sigmac -I --target sumologic -c tools/config/sumologic-sourcecategory.yml --backend-config tests/sumologic_json_backend_config.yml $f;
    done
