language: python
dist: xenial
python:
  - 3.6
  - 3.7
sudo: true
cache: pip

install:
  - pip install -r tools/requirements-devel.txt 
  - pip install .

script:
  - for f in `find rules -iname '*.yml'`; do
      sigmac --target sumologic -c tools/config/sumologic.yml $f;
    done
