# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Sigma Tools and Rule Tests

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [ master ]

jobs:
  test-sigma:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tools/requirements.txt -r tools/requirements-devel.txt
    - name: Test Sigma Tools and Rules
      run: |
        make test
    - name: Test SQL(ite) Backend
      run: |
        make test-backend-sql
